# -*- coding: utf-8 -*-
"""AI_Ad_Generator_Complete_Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zac3275_PHw3tUWUg88ZlC7PmG-GrRGy

# AI Ad Generator - All 4 Tools Worker

This notebook runs all 4 tools from Google Colab:
- **Tool 1**: Text → Image (Stable Diffusion)
- **Tool 2**: Image → Image (Stable Diffusion)
- **Tool 3**: Image → Text (Custom BLIP)
- **Tool 4**: Price Recommendation (SentenceTransformer + Random Forest)

**Instructions:**
1. Change Runtime → Change runtime type → T4 GPU
2. Run all cells in order
3. Leave the last cell running (worker loop)
4. Start your Flask app locally
5. All tools will process through this Colab worker

## Cell 1: Mount Drive and Set Paths
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Image tools base (SD, BLIP, requests/results)
BASE_DIR = "/content/drive/My Drive/ai_ad_generator"
SD_MODELS_DIR = f"{BASE_DIR}/models/sd15"
BLIP_MODELS_DIR = f"{BASE_DIR}/models/custom_product_caption_v2"
REQUESTS_DIR = f"{BASE_DIR}/requests"
RESULTS_DIR = f"{BASE_DIR}/results"

# Price model lives directly under My Drive (different location)
PRICE_MODEL_DIR = "/content/drive/My Drive/ai_price_model_v2"
PRICE_META_PATH = f"{PRICE_MODEL_DIR}/meta.json"

import os
os.makedirs(REQUESTS_DIR, exist_ok=True)
os.makedirs(RESULTS_DIR, exist_ok=True)

print("="*60)
print("PATHS CONFIGURED")
print("="*60)
print("Base:", BASE_DIR)
print("SD Models:", SD_MODELS_DIR)
print("BLIP Models:", BLIP_MODELS_DIR)
print("Price Model:", PRICE_MODEL_DIR)
print("Requests:", REQUESTS_DIR)
print("Results:", RESULTS_DIR)
print("="*60)

"""## Cell 2: Install Required Libraries"""

!pip install -q diffusers transformers accelerate safetensors sentence-transformers scikit-learn joblib
print("✓ All libraries installed successfully")

"""## Cell 3: Load Stable Diffusion Pipelines (Tools 1, 2, 5)"""

import torch
from diffusers import StableDiffusionPipeline, StableDiffusionImg2ImgPipeline, StableDiffusionInpaintPipeline

print("Loading Stable Diffusion pipelines from Drive...")

# Text-to-Image pipeline (Tool 1)
sd_pipe = StableDiffusionPipeline.from_pretrained(
    SD_MODELS_DIR,
    torch_dtype=torch.float16,
    safety_checker=None,
)
sd_pipe.to("cuda")
print("✓ Text-to-Image pipeline loaded")

# Image-to-Image pipeline (Tool 2) - FIX: Use dedicated Img2Img pipeline
img2img_pipe = StableDiffusionImg2ImgPipeline.from_pretrained(
    SD_MODELS_DIR,
    torch_dtype=torch.float16,
    safety_checker=None,
)
img2img_pipe.to("cuda")
print("✓ Image-to-Image pipeline loaded")

# Inpainting pipeline (Tool 5) - Load from same model, works for basic inpainting
inpaint_pipe = StableDiffusionInpaintPipeline.from_pretrained(
    SD_MODELS_DIR,
    torch_dtype=torch.float16,
    safety_checker=None,
)
inpaint_pipe.to("cuda")
print("✓ Inpainting pipeline loaded")

print("✓ All Stable Diffusion pipelines ready on GPU")

"""## Cell 4: Load BLIP Model (Tool 3)"""

from transformers import BlipProcessor, BlipForConditionalGeneration

print("Loading custom BLIP product caption model from Drive...")

blip_processor = BlipProcessor.from_pretrained(BLIP_MODELS_DIR)
blip_model = BlipForConditionalGeneration.from_pretrained(BLIP_MODELS_DIR)
blip_model.to("cuda")

print("✓ BLIP model loaded and ready on GPU")

"""## Cell 5: Load Price Prediction Models (Tool 4)"""

import json
from pathlib import Path
import joblib
import numpy as np
from sentence_transformers import SentenceTransformer
import os

# Declare global variables first (IMPORTANT!)
price_embedder = None
price_models = {}
price_models_info = {}

print("\n" + "="*60)
print("LOADING PRICE PREDICTION MODELS (Tool 4)")
print("="*60)
print("PRICE_MODEL_DIR:", PRICE_MODEL_DIR)
print("PRICE_META_PATH:", PRICE_META_PATH)
print("meta.json exists:", os.path.exists(PRICE_META_PATH))

if not os.path.exists(PRICE_META_PATH):
    raise FileNotFoundError(f"meta.json not found at {PRICE_META_PATH}")

# Load meta.json
with open(PRICE_META_PATH, "r", encoding="utf-8") as f:
    meta = json.load(f)

# Load sentence transformer embedder
embed_model_name = meta.get("embed_model_name", "sentence-transformers/all-MiniLM-L6-v2")
print(f"\nLoading embedder: {embed_model_name}")
price_embedder = SentenceTransformer(embed_model_name)
print("✓ Embedder loaded successfully")

# Load category-specific models
price_models_info = meta.get("models_info", {})
models_dir = os.path.join(PRICE_MODEL_DIR, "models_by_category")

print(f"\nmodels_by_category path: {models_dir}")
print(f"models_by_category exists: {os.path.exists(models_dir)}")

if os.path.exists(models_dir):
    print(f"Files in models_by_category: {os.listdir(models_dir)}")

print(f"\nLoading {len(price_models_info)} category models...")
for cat, info in price_models_info.items():
    model_filename = os.path.basename(info["model_path"])
    model_path = os.path.join(models_dir, model_filename)

    print(f"  → Category: {cat}")
    print(f"    File: {model_filename}")
    print(f"    Exists: {os.path.exists(model_path)}", end="")

    if not os.path.exists(model_path):
        print(" ⚠️  SKIPPED (file not found)")
        continue

    try:
        price_models[cat] = joblib.load(model_path)
        print(" ✓ Loaded")
    except Exception as e:
        print(f" ✗ ERROR: {e}")

print("\n" + "="*60)
print("PRICE MODELS LOADED")
print("="*60)
print(f"Embedder: {'✓ Loaded' if price_embedder else '✗ Not loaded'}")
print(f"Categories loaded: {len(price_models)}")
print(f"Available categories: {', '.join(price_models.keys())}")
print("="*60 + "\n")

"""## Cell 6: Define Job Processor Function"""

from PIL import Image
import json
from pathlib import Path
import numpy as np

def process_job(job_path: Path):
    """Process a single job from the requests folder."""
    global price_embedder, price_models

    with open(job_path, "r", encoding="utf-8") as f:
        job = json.load(f)

    job_id = job["job_id"]
    mode = job.get("mode", "txt2img")

    print(f"\n{'='*60}")
    print(f"Processing job: {job_id} | Mode: {mode}")
    print("="*60)

    # ============================================================
    # Tool 1: Text-to-Image (Stable Diffusion) - FIXED
    # ============================================================
    if mode == "txt2img":
        prompt = job["prompt"]
        width = job["width"]
        height = job["height"]

        print(f"Text-to-Image: {width}x{height}")
        print(f"Prompt: {prompt}")

        # FIX: Increased steps to 50 and added negative_prompt
        negative_prompt = "blurry, low quality, deformed, ugly, bad anatomy, disfigured, poorly drawn face, mutation, mutated, extra limbs, poorly drawn hands, missing limbs, blur, duplicate, watermark, text"
        
        image = sd_pipe(
            prompt,
            negative_prompt=negative_prompt,
            width=width,
            height=height,
            num_inference_steps=50,  # FIX: Increased from 28
            guidance_scale=7.5,
        ).images[0]

        out_path = Path(RESULTS_DIR) / f"{job_id}.png"
        image.save(out_path)
        print(f"✓ Image saved to: {out_path}")

    # ============================================================
    # Tool 2: Image-to-Image (Stable Diffusion) - FIXED
    # ============================================================
    elif mode == "img2img":
        prompt = job["prompt"]
        width = job["width"]
        height = job["height"]
        strength = job.get("strength", 0.6)  # FIX: Changed default from 0.4 to 0.6

        input_path = Path(REQUESTS_DIR) / f"{job_id}_input.png"
        if not input_path.exists():
            print(f"✗ Input image not found: {input_path}")
            job_path.unlink(missing_ok=True)
            return

        print(f"Image-to-Image: {width}x{height} | Strength: {strength}")
        print(f"Prompt: {prompt}")

        init_image = Image.open(input_path).convert("RGB")
        init_image = init_image.resize((width, height))

        # FIX: Use dedicated img2img_pipe instead of sd_pipe
        image = img2img_pipe(
            prompt=prompt,
            image=init_image,
            strength=strength,
            num_inference_steps=50,  # FIX: Increased from 28
            guidance_scale=7.5,
        ).images[0]

        out_path = Path(RESULTS_DIR) / f"{job_id}.png"
        image.save(out_path)
        input_path.unlink(missing_ok=True)
        print(f"✓ Image saved to: {out_path}")

    # ============================================================
    # Tool 3: Image-to-Text (Custom BLIP) - FIXED
    # ============================================================
    elif mode == "img2text":
        input_path = Path(REQUESTS_DIR) / f"{job_id}_input.png"
        if not input_path.exists():
            print(f"✗ Input image not found: {input_path}")
            job_path.unlink(missing_ok=True)
            return

        print("Image-to-Text: Generating product description...")

        image = Image.open(input_path).convert("RGB")

        inputs = blip_processor(image, return_tensors="pt").to("cuda")
        # FIX: Increased max_length to 150 and added min_length=30
        output = blip_model.generate(**inputs, max_length=150, min_length=30)
        description = blip_processor.decode(output[0], skip_special_tokens=True)

        result = {"description": description}
        out_path = Path(RESULTS_DIR) / f"{job_id}.json"
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(result, f)

        input_path.unlink(missing_ok=True)
        print(f"✓ Description: {description}")
        print(f"✓ Result saved to: {out_path}")

    # ============================================================
    # Tool 4: Price Recommendation
    # ============================================================
    elif mode == "price":
        product_name = job.get("product_name", "")
        brand = job.get("brand", "")
        category = job.get("category", "")
        material = job.get("material", "")
        color = job.get("color", "")
        rating = job.get("rating", 4.5)
        num_reviews = job.get("num_reviews", 0)

        print(f"Price Recommendation:")
        print(f"  Product: {product_name}")
        print(f"  Brand: {brand}")
        print(f"  Category: {category}")
        print(f"  Rating: {rating} ({num_reviews} reviews)")

        if price_embedder is None or not price_models:
            print("✗ Price models not loaded")
            result = {"success": False, "error": "Price models not loaded"}
        elif category not in price_models:
            available_cats = ', '.join(price_models.keys())
            print(f"✗ No model for category '{category}'")
            print(f"  Available: {available_cats}")
            result = {
                "success": False,
                "error": f"No model for category: {category}. Available: {available_cats}"
            }
        else:
            # Create feature text
            text = ", ".join([
                product_name,
                f"brand {brand}",
                f"category {category}",
                f"material {material}",
                f"color {color}",
                f"rating {rating}",
                f"{num_reviews} reviews",
            ])

            # Generate embedding and predict
            emb = price_embedder.encode([text])
            reg = price_models[category]
            log_price = reg.predict(emb)[0]
            price = float(np.exp(log_price))

            # Calculate range
            lower = round(price * 0.9, 2)
            upper = round(price * 1.1, 2)

            result = {
                "success": True,
                "price": round(price, 2),
                "range": [lower, upper],
            }
            print(f"✓ Predicted price: ${result['price']}")
            print(f"  Range: ${lower} - ${upper}")

        out_path = Path(RESULTS_DIR) / f"{job_id}.json"
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(result, f)
        print(f"✓ Result saved to: {out_path}")

    # ============================================================
    # Tool 5: Inpainting / Magic Eraser (NEW)
    # ============================================================
    elif mode == "inpainting":
        input_path = Path(REQUESTS_DIR) / f"{job_id}_input.png"
        mask_path = Path(REQUESTS_DIR) / f"{job_id}_mask.png"
        prompt = job.get("prompt", "clean background, seamless, high quality")

        if not input_path.exists():
            print(f"✗ Input image not found: {input_path}")
            job_path.unlink(missing_ok=True)
            return

        if not mask_path.exists():
            print(f"✗ Mask image not found: {mask_path}")
            job_path.unlink(missing_ok=True)
            return

        print("Inpainting: Removing objects from image...")
        print(f"Prompt: {prompt}")

        # Load and resize images to 512x512 (required for SD inpainting)
        input_image = Image.open(input_path).convert("RGB")
        mask_image = Image.open(mask_path).convert("RGB")
        
        input_image = input_image.resize((512, 512))
        mask_image = mask_image.resize((512, 512))

        # Run inpainting
        result_image = inpaint_pipe(
            prompt=prompt,
            image=input_image,
            mask_image=mask_image,
            num_inference_steps=50,
            guidance_scale=7.5,
        ).images[0]

        out_path = Path(RESULTS_DIR) / f"{job_id}.png"
        result_image.save(out_path)
        
        # Clean up input files
        input_path.unlink(missing_ok=True)
        mask_path.unlink(missing_ok=True)
        print(f"✓ Inpainted image saved to: {out_path}")

    # ============================================================
    # Tool 6: Avatar / Virtual Try-On (IMPROVED V2)
    # ============================================================
    elif mode == "avatar":
        avatar_path = Path(REQUESTS_DIR) / f"{job_id}_avatar.png"
        product_path = Path(REQUESTS_DIR) / f"{job_id}_product.png"
        
        # Get user-provided prompt or use default with product type
        product_type = job.get("product_type", "bag")
        default_prompt = f"medium shot of a person holding a {product_type} in their hands, arms extending to hold the object, natural grip, fingers visible on handle, professional fashion photography, 8k"
        user_prompt = job.get("prompt", "").strip()
        holding_prompt = user_prompt if user_prompt else default_prompt

        if not avatar_path.exists():
            print(f"✗ Avatar image not found: {avatar_path}")
            job_path.unlink(missing_ok=True)
            return

        if not product_path.exists():
            print(f"✗ Product image not found: {product_path}")
            job_path.unlink(missing_ok=True)
            return

        print("Avatar: Creating virtual try-on with holding mechanics...")
        print(f"Product Type: {product_type}")

        # Load images
        avatar_image = Image.open(avatar_path).convert("RGBA")
        product_image = Image.open(product_path).convert("RGBA")

        # Resize avatar to 512x512
        avatar_image = avatar_image.resize((512, 512))
        
        # Resize product to fit on avatar (about 45% of avatar size for better proportions)
        product_w = int(512 * 0.45)
        product_h = int(product_image.height * (product_w / product_image.width))
        product_image = product_image.resize((product_w, product_h))

        # BETTER POSITIONING: Paste product in center-lower third (y = 200-300 range)
        # This places the bag over the avatar's torso, where they would naturally hold it
        composite = avatar_image.copy()
        paste_x = (512 - product_w) // 2
        paste_y = 250  # Center-lower third of canvas (around stomach/chest level)
        
        # Paste with alpha channel for transparency
        composite.paste(product_image, (paste_x, paste_y), product_image)
        composite_rgb = composite.convert("RGB")

        # NEGATIVE PROMPT: Prevent floating objects and bad anatomy
        negative_prompt = "floating object, levitating, missing arms, missing hands, disconnected body, amputation, bad anatomy, deformed hands, extra fingers, missing fingers, blurry, low quality"
        
        print(f"Prompt: {holding_prompt}")
        print(f"Negative: {negative_prompt}")
        print(f"Strength: 0.75 (high for hallucinating arms/hands)")

        # Run through img2img with HIGHER STRENGTH (0.75) to allow AI more freedom
        # to hallucinate new pixels like arms and hands
        blended = img2img_pipe(
            prompt=holding_prompt,
            negative_prompt=negative_prompt,
            image=composite_rgb,
            strength=0.75,  # Higher strength for generating arms/hands
            num_inference_steps=50,  # More steps for better quality
            guidance_scale=8.0,  # Slightly higher guidance for prompt adherence
        ).images[0]

        out_path = Path(RESULTS_DIR) / f"{job_id}.png"
        blended.save(out_path)
        
        # Clean up input files
        avatar_path.unlink(missing_ok=True)
        product_path.unlink(missing_ok=True)
        print(f"✓ Virtual try-on image saved to: {out_path}")

    # ============================================================
    # Unknown mode
    # ============================================================
    else:
        print(f"✗ Unknown mode: {mode}")
        job_path.unlink(missing_ok=True)
        return

    # Clean up job file
    job_path.unlink(missing_ok=True)
    print(f"✓ Job {job_id} completed successfully")
    print("="*60)

print("✓ Job processor function defined")

"""## Cell 7: Start Worker Loop (Keep Running)"""

import time
from pathlib import Path

print("\n" + "="*60)
print("🚀 AI AD GENERATOR WORKER - ALL 6 TOOLS ACTIVE")
print("="*60)
print("Tool 1: Text → Image (Stable Diffusion) - FIXED")
print("Tool 2: Image → Image (Stable Diffusion) - FIXED")
print("Tool 3: Image → Text (Custom BLIP Model) - FIXED")
print("Tool 4: Price Recommendation (SentenceTransformer + RF)")
print("Tool 5: Magic Eraser / Inpainting (NEW)")
print("Tool 6: Virtual Try-On / Avatar (NEW)")
print("="*60)
print(f"\nWatching: {REQUESTS_DIR}")
print(f"Results: {RESULTS_DIR}")
print("\n⚠️  KEEP THIS CELL RUNNING")
print("⚠️  Start your Flask app locally to submit jobs")
print("\nWorker loop started. Waiting for jobs...\n")

job_count = 0

while True:
    try:
        request_files = sorted(Path(REQUESTS_DIR).glob("*.json"))

        if not request_files:
            time.sleep(5)
            continue

        for job_file in request_files:
            try:
                job_count += 1
                print(f"\n[Job #{job_count}] Found: {job_file.name}")
                process_job(job_file)
            except Exception as e:
                print(f"\n{'='*60}")
                print(f"✗ ERROR processing {job_file.name}")
                print(f"Error: {e}")
                print("="*60)
                import traceback
                traceback.print_exc()
                # Clean up failed job
                job_file.unlink(missing_ok=True)

        time.sleep(2)

    except KeyboardInterrupt:
        print("\n\n⚠️  Worker stopped by user")
        break
    except Exception as e:
        print(f"\n✗ CRITICAL ERROR in worker loop: {e}")
        import traceback
        traceback.print_exc()
        time.sleep(10)
        print("Restarting worker loop...\n")